### ISSUE TITLE
Does not get found by Zeroconf on Windows

### ISSUE THREAD

**Issue by shaddow501** [probonopd/WirelessPrinting#28] opened 2017-11-08 21:53 UTC
I have programmed your code but I cant find out how to connect?? how to I find out the IP?

**Comment by probonopd** [comment] 2017-11-08 22:11
The Cura Octoprint plugin and PrusaControl should find the printer automatically using Zeroconf/Bonjour. No need to manually enter an IP address.

**Comment by shaddow501** [comment] 2017-11-08 22:43
So I do not need to configure  this?
![octoprint](https://user-images.githubusercontent.com/21113491/32578738-0c95de30-c4e7-11e7-929a-74020bb68b39.jpg)

**Comment by probonopd** [comment] 2017-11-09 18:50
No

**Comment by probonopd** [comment] 2017-11-09 18:52
I notice you are using Windows. Not sure about that. I have no Windows, am not interested in supporting it, and don't know how well Cura OctoPrint plugin works on Windows for detecting printers via Zeroconf. Maybe https://github.com/fieldOfView/OctoPrintPlugin knows.

**Comment by weidmane** [comment] 2018-02-14 20:33
https://learn.adafruit.com/bonjour-zeroconf-networking-for-windows-and-linux/overview

**Comment by probonopd** [comment] 2018-02-16 20:39
@weidmane thanks for the hint. Does it work for you if you follow that guide? As said above,

> I have no Windows, am not interested in supporting it

but if you can send a pull request that makes it work on Windows (and doesn't break it) I'm happy to include it. Thanks.

**Comment by probonopd** [comment] 2018-04-09 19:34
> how to I find out the IP?

The IP should be displayed on the display of your printer. Is it?

**Comment by fieldOfView** [comment] 2019-02-26 09:24
For the record, the Cura OctoPrint Connection plugin uses a python-based implementation of Bonjour/Zeroconf, so it does not need an additional install on Windows.

**Comment by probonopd** [comment] 2019-02-28 20:09
I can confirm that on Windows 10 the WirelessPrinting instance is not found by Cura 3.6 with the OctoPrint Plugin 3.5.4.

On Linux it works.

**Comment by cpeuschel** [comment] 2020-03-16 19:46
Couldnt reproduce that on Cura 4.5 with OctoPrint Plugin 3.5.12
![image](https://user-images.githubusercontent.com/11633293/76794352-1e233c80-67c7-11ea-8cd4-b8edb5365085.png)

**Comment by probonopd** [comment] 2020-03-16 20:41
Thank you very much for testing @cpeuschel. Closing for now, unless someone reports to reproduce the issue.

**Closed by probonopd** 2020-03-16 20:41 UTC
