### ISSUE TITLE
Printer won't start printing with Cura

### ISSUE THREAD

**Issue by cpeuschel** [probonopd/WirelessPrinting#142] opened 2020-02-29 00:31 UTC
im using Cura 4.5 and OctoPrint Version 3.5.12 on Mac OS Catalina (10.15.3) and the Continuous build on my esp8266. 
if i click "print with OctoPrint", the gcode is uploading and the LCD says "Receiving..." while the upload is done it says "Received" and than nothing happens.

Telnet Output: 
>M105
<ok T:20.62 /0.00 B:32.47 /0.00 @:0 B@:0#ok#
>M117 Receiving...
<ok#ok#
>M117 Receiving...
<ok#ok#
>M105
<ok T:20.62 /0.00 B:29.80 /0.00 @:0 B@:0#ok#
>M105
<ok T:20.62 /0.00 B:29.32 /0.00 @:0 B@:0#ok#
>M105
<ok T:20.62 /0.00 B:27.39 /0.00 @:0 B@:0#ok#
>M105
<ok T:20.62 /0.00 B:28.84 /0.00 @:0 B@:0#ok#
>M105
<ok T:20.62 /0.00 B:29.80 /0.00 @:0 B@:0#ok#
>M105
<ok T:20.62 /0.00 B:27.87 /0.00 @:0 B@:0#ok#
>M117 Received
<ok#ok#
>M105
<ok T:20.62 /0.00 B:27.87 /0.00 @:0 B@:0#ok#

if i start the print directly on "http://the-ip-address/" the printer starts the print.

**Comment by probonopd** [comment] 2020-03-07 09:10
I suspect Cura is not sending the `print` parameter:

https://github.com/probonopd/WirelessPrinting/blob/bad8e5166a2f1bbad95a4fb8849b08d1edfc7d3a/ESP8266WirelessPrintAsync/ESP8266WirelessPrintAsync.ino#L685-L692

Can you find a way to see the request that Cura is sending?

**Comment by probonopd** [comment] 2020-03-07 09:12
> OctoPrint Version 3.5.12

WirelessPrinting does not use nor need OctoPrint; it is a smaller implementation of it that goes on the ESP8266.

Which Cura plugin and version do you use to send the gcode to the printer?

**Comment by cpeuschel** [comment] 2020-03-07 14:47
> Which Cura plugin and version do you use to send the gcode to the printer?
Im Using Cura 4.5 with the OctoPrint Plugin Version 3.5.12

**Comment by cpeuschel** [comment] 2020-03-07 14:48
> Can you find a way to see the request that Cura is sending?

Maybe with Wireshark. I will check this

**Comment by probonopd** [comment] 2020-03-07 15:13
> Im Using Cura 4.5 with the OctoPrint Connection Plugin Version 3.5.12

Ah ok, somehow I was under the impression that one always needs a version of Cura-OctoPrintPlugin that matches Cura, but apparently this is (no longer?) the case.

**Comment by cpeuschel** [comment] 2020-03-07 15:17
Cura doesn't send the POST parameter "print", but why?

**Comment by probonopd** [comment] 2020-03-07 15:18
Great question. I am trying to reproduce it.

**Comment by probonopd** [comment] 2020-03-07 15:20
I can reproduce the issue with  Cura 4.5 and the OctoPrint Connection Plugin Version 3.5.12.

It also gives me this:

![error](https://user-images.githubusercontent.com/2480569/76146024-2b358280-6087-11ea-82f4-37101b356cf2.png)

**Comment by cpeuschel** [comment] 2020-03-07 15:22
do u have discord? then we can debug this Problem and post the answer as a comment if we solved the Problem.

**Comment by probonopd** [comment] 2020-03-07 15:25
Same issue with Cura 4.4.1 and the OctoPrint Connection Plugin Version 3.5.12.
I suspect something in the OctoPrint Connection Plugin has changed.

**Comment by probonopd** [comment] 2020-03-07 15:34
* Power cycle printer if stuck on "Received"
* Close Cura

```
rm -rf ~/.local/share/cura/4.5/plugins/OctoPrintPlugin/*`
cd ~/.local/share/cura/4.5/plugins/OctoPrintPlugin
git clone https://github.com/fieldOfView/Cura-OctoPrintPlugin
cd Cura-OctoPrintPlugin/
git checkout 3cef0a9
```
* Restart Cura

__Works__

**Comment by probonopd** [comment] 2020-03-07 15:38
Can you post the POST request from a working and a non-working version for comparison?

**Comment by probonopd** [comment] 2020-03-07 15:41
Here something was changed regarding the print parameter:

https://github.com/fieldOfView/Cura-OctoPrintPlugin/commit/ab40c033cb36115575380c234340b893df091aad

**Comment by probonopd** [comment] 2020-03-07 15:54
I have opened tickets in the https://github.com/fieldOfView/Cura-OctoPrintPlugin project, let's continue there.

**Comment by probonopd** [comment] 2020-03-07 16:56
According to https://github.com/fieldOfView/Cura-OctoPrintPlugin/issues/156#issuecomment-596106186 it looks like we either need to support that additional "start printing" command, or just comment out the `if (request->hasParam("print", true))` condition so that we always start printing regardless of whether the client requests it or not.

**Comment by cpeuschel** [comment] 2020-03-07 17:03
Maybe we have to develop an Cura Plugin?

**Comment by probonopd** [comment] 2020-03-07 18:52
Fixed in the latest build. Thanks for reporting @cpeuschel

**Closed by probonopd** 2020-03-07 18:52 UTC
